
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compi2.usac.analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int id = 4;
  public static final int equals = 2;
  public static final int semiColon = 10;
  public static final int number = 5;
  public static final int minus = 7;
  public static final int EOF = 0;
  public static final int colon = 11;
  public static final int plus = 6;
  public static final int by = 8;
  public static final int entero = 3;
  public static final int error = 1;
  public static final int divided = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "equals",
  "entero",
  "id",
  "number",
  "plus",
  "minus",
  "by",
  "divided",
  "semiColon",
  "colon"
  };
}

